# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 10, 18, 45, 32, 776371, tzinfo=utc), verbose_name='created date'),
            preserve_default=False,
        ),
    ]
